# Generated by Django 5.2.5 on 2025-08-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0002_attendee_event_eventregistration_event_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='views_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('music-arts', 'Music & Arts'), ('business', 'Business & Professional'), ('sports', 'Sports & Fitness'), ('technology', 'Technology'), ('food-drink', 'Food & Drink'), ('health-wellness', 'Health & Wellness'), ('education', 'Education & Learning'), ('community', 'Community & Culture'), ('charity', 'Charity & Fundraising'), ('government', 'Government & Politics'), ('tourism', 'Tourism & Hospitality')], max_length=80),
        ),
    ]
