# Generated by Django 5.2 on 2025-08-27 09:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0003_event_views_count_alter_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('organizer', 'Organizer'), ('attendee', 'Attendee')], default='organizer', max_length=20),
        ),
        migrations.CreateModel(
            name='EventFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorited_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_favorites', to='event_app.attendee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='event_app.event')),
            ],
            options={
                'verbose_name': 'Event Favorite',
                'verbose_name_plural': 'Event Favorites',
                'ordering': ['-favorited_at'],
                'unique_together': {('attendee', 'event')},
            },
        ),
    ]
