# Generated by Django 5.2.5 on 2025-09-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0006_event_max_attendees_event_registration_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitem',
            name='category',
            field=models.CharField(choices=[('venue', 'Venue'), ('catering', 'Catering'), ('decor', 'Decor'), ('program', 'Program')], max_length=20),
        ),
    ]
