# Generated by Django 5.2.5 on 2025-09-01 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0007_alter_budgetitem_category'),
        ('event_app', '0007_notification'),
    ]

    operations = [
    ]
