# Generated by Django 5.2.5 on 2025-09-03 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0009_alter_event_status_rejection'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to='event_app.event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registered_at'],
                'unique_together': {('event', 'email')},
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Field label shown to users', max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Text Area'), ('email', 'Email'), ('phone', 'Phone Number'), ('number', 'Number'), ('date', 'Date'), ('datetime', 'Date and Time'), ('select', 'Dropdown Select'), ('radio', 'Radio Buttons'), ('checkbox', 'Checkboxes'), ('boolean', 'Yes/No Checkbox'), ('file', 'File Upload')], max_length=30)),
                ('placeholder', models.CharField(blank=True, help_text='Placeholder text for input fields', max_length=200)),
                ('help_text', models.CharField(blank=True, help_text='Additional help text for users', max_length=500)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0, help_text='Field display order')),
                ('choices', models.TextField(blank=True, help_text='JSON array of choices for select/radio/checkbox fields. Example: ["Option 1", "Option 2"]')),
                ('min_length', models.PositiveIntegerField(blank=True, null=True)),
                ('max_length', models.PositiveIntegerField(blank=True, null=True)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='event_app.event')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_value', models.TextField(blank=True, null=True)),
                ('number_value', models.FloatField(blank=True, null=True)),
                ('date_value', models.DateField(blank=True, null=True)),
                ('datetime_value', models.DateTimeField(blank=True, null=True)),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
                ('file_value', models.FileField(blank=True, null=True, upload_to='registration_files/')),
                ('selected_choices', models.TextField(blank=True, help_text='JSON array of selected choices')),
                ('form_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_app.formfield')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='event_app.eventregistrations')),
            ],
            options={
                'unique_together': {('registration', 'form_field')},
            },
        ),
    ]
