# Generated by Django 5.2.5 on 2025-09-07 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0010_eventregistrations_formfield_registrationfieldvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
    ]
