# Generated by Django 5.2.5 on 2025-09-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0011_remove_event_attendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='budgetitem',
            name='description',
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
