# Generated by Django 5.2.5 on 2025-09-09 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0013_event_attendees_alter_eventregistration_attendee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfavorite',
            name='attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Attendee',
        ),
    ]
