# Generated by Django 5.2.5 on 2025-09-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0014_alter_eventfavorite_attendee_delete_attendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
